# Generated by Django 5.1 on 2024-09-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='price',
            new_name='precio',
        ),
    ]
