# Generated by Django 5.1 on 2024-09-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_rename_price_productos_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='clasificacion',
            new_name='calificacion',
        ),
        migrations.AddField(
            model_name='productos',
            name='numeroReseñas',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
