# Generated by Django 5.1 on 2024-09-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_rename_clasificacion_productos_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='numeroReseñas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
