# Generated by Django 5.1 on 2024-10-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0005_order_orderitem_review_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qty',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='calificacion',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='comentarios',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='producto',
        ),
    ]
